/**
 * Server-side question bank (ready for a very large bank):
 * 1. questions.base_number — "17" for 17(b)(i): parts of one paper question group by (paper_id, base_number).
 *    Generated by MySQL from `number`, so it is always right.
 * 2. questions.search_text — plain searchable words (question, options, mark scheme, topic, keywords, paper),
 *    filled by the API; FULLTEXT-indexed for search.
 * 3. Indexes for every student filter and sort.
 */

/** @param {import('knex').Knex} knex */
export async function up(knex) {
  await knex.raw(
    "ALTER TABLE `questions` ADD COLUMN `base_number` VARCHAR(20) GENERATED ALWAYS AS (COALESCE(NULLIF(TRIM(SUBSTRING_INDEX(`number`, '(', 1)), ''), `number`)) STORED AFTER `number`",
  );
  await knex.raw("ALTER TABLE `questions` ADD COLUMN `search_text` MEDIUMTEXT NULL COMMENT 'Plain searchable words, kept by the API' AFTER `text`");
  await knex.raw('ALTER TABLE `questions` ADD FULLTEXT INDEX `ft_questions_search` (`search_text`)');
  await knex.schema.alterTable('questions', (t) => {
    t.index(['paper_id', 'base_number'], 'questions_paper_base_index');
    t.index(['status', 'deleted_at', 'paper_id'], 'questions_status_deleted_paper_index');
    t.index(['marks'], 'questions_marks_index');
    t.index(['type'], 'questions_type_index');
  });
  await knex.schema.alterTable('papers', (t) => {
    t.index(['status', 'subject_id', 'year'], 'papers_status_subject_year_index');
    t.index(['season_code'], 'papers_season_index');
  });
}

/** @param {import('knex').Knex} knex */
export async function down(knex) {
  await knex.schema.alterTable('papers', (t) => {
    t.dropIndex([], 'papers_status_subject_year_index');
    t.dropIndex([], 'papers_season_index');
  });
  await knex.schema.alterTable('questions', (t) => {
    t.dropIndex([], 'questions_paper_base_index');
    t.dropIndex([], 'questions_status_deleted_paper_index');
    t.dropIndex([], 'questions_marks_index');
    t.dropIndex([], 'questions_type_index');
  });
  await knex.raw('ALTER TABLE `questions` DROP INDEX `ft_questions_search`');
  await knex.raw('ALTER TABLE `questions` DROP COLUMN `search_text`, DROP COLUMN `base_number`');
}
